# Generated by Django 4.0.4 on 2022-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_user_adress_user_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttranscript',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
