# Generated by Django 4.0.4 on 2022-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_formapply_email_alter_award_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='formapply',
            name='status',
            field=models.IntegerField(),
        ),
    ]
