# Generated by Django 4.0.4 on 2022-05-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_formapply_email_alter_award_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapply',
            options={'ordering': ['-point']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='clas',
            new_name='masv',
        ),
        migrations.AddField(
            model_name='formapply',
            name='point',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='formapply',
            name='context',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='formapply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
