# Generated by Django 4.0.4 on 2022-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_formapply_options_formapply_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapply',
            name='context',
            field=models.FileField(default=None, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='formapply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
