# Generated by Django 4.0.4 on 2022-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_alter_formapply_context_alter_formapply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapply',
            name='context',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
