# Generated by Django 4.0.4 on 2022-05-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_alter_formapply_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapply',
            options={'ordering': ['-point']},
        ),
    ]
